<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251021161810 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, state_id VARCHAR(255) DEFAULT NULL, state_code VARCHAR(255) DEFAULT NULL, state_name VARCHAR(255) DEFAULT NULL, country_code VARCHAR(255) DEFAULT NULL, country_name VARCHAR(255) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, native VARCHAR(255) DEFAULT NULL, timezone VARCHAR(255) DEFAULT NULL, wiki_data_id VARCHAR(255) NOT NULL, country_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2D5B0234D8A48BBD ON city (country_id_id)');
        $this->addSql('CREATE TABLE country (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, iso3 VARCHAR(255) NOT NULL, iso2 VARCHAR(255) NOT NULL, numeric_code VARCHAR(255) NOT NULL, phonecode VARCHAR(255) NOT NULL, capital VARCHAR(255) DEFAULT NULL, currency VARCHAR(255) NOT NULL, currency_name VARCHAR(255) NOT NULL, currency_symbol VARCHAR(255) NOT NULL, tld VARCHAR(255) NOT NULL, native VARCHAR(255) NOT NULL, population VARCHAR(255) DEFAULT NULL, gdp VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, subregion VARCHAR(255) DEFAULT NULL, nationality VARCHAR(255) DEFAULT NULL, timezones TEXT DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, emoji VARCHAR(255) DEFAULT NULL, emoji_u VARCHAR(255) DEFAULT NULL, wiki_data_id VARCHAR(255) NOT NULL, region_id_id INT DEFAULT NULL, subregion_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5373C966C7209D4F ON country (region_id_id)');
        $this->addSql('CREATE INDEX IDX_5373C9667C645A2F ON country (subregion_id_id)');
        $this->addSql('CREATE TABLE region (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, wiki_data_id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sub_region (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, wiki_data_id VARCHAR(255) NOT NULL, region_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BD33BE3AC7209D4F ON sub_region (region_id_id)');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234D8A48BBD FOREIGN KEY (country_id_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966C7209D4F FOREIGN KEY (region_id_id) REFERENCES region (id)');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C9667C645A2F FOREIGN KEY (subregion_id_id) REFERENCES sub_region (id)');
        $this->addSql('ALTER TABLE sub_region ADD CONSTRAINT FK_BD33BE3AC7209D4F FOREIGN KEY (region_id_id) REFERENCES region (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE city DROP CONSTRAINT FK_2D5B0234D8A48BBD');
        $this->addSql('ALTER TABLE country DROP CONSTRAINT FK_5373C966C7209D4F');
        $this->addSql('ALTER TABLE country DROP CONSTRAINT FK_5373C9667C645A2F');
        $this->addSql('ALTER TABLE sub_region DROP CONSTRAINT FK_BD33BE3AC7209D4F');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE sub_region');
    }
}
